---

- yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "ntp"
  when:
    - "ntp_server is defined"

- yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - "ntp"
  when:
    - "not ntp_server is defined"
