#!/usr/bin/ansible-playbook --inventory-file=inventories/lon.yml
---

- hosts: all
  roles:
#  - { role: ansible }
  - { role: named }
#  - { role: network }
#  - { role: ntp }
#  - { role: storage }
#  - { role: docker }
#  - { role: users }
