---

- file:
    path:  "/etc/systemd/system/{{ service.name }}.d"
    state: directory
  when:
    - "(service.wants is defined and service.wants|length > 0) or (service.after is defined and service.after|length > 0) or (service.execstartpre is defined and service.execstartpre|length > 0)"

- template:
    src: "service.overrides.j2"
    dest: "/etc/systemd/system/{{ service.name }}.d/{{ service.override }}.conf"
  when:
    - "(service.wants is defined and service.wants|length > 0) or (service.after is defined and service.after|length > 0) or (service.execstartpre is defined and service.execstartpre|length > 0)"
