---
- yum:
    name:  "{{ item }}"
    state: "present"
  with_items:
    - "bzip2"
    - "unzip"

- get_url:
    url:        "https://github.com/restic/restic/releases/download/v0.8.3/restic_0.8.3_linux_amd64.bz2"
    dest:       "/usr/local/src/restic_0.8.3_linux_amd64.bz2"
    checksum:   "sha256:1e9aca80c4f4e263c72a83d4333a9dac0e24b24e1fe11a8dc1d9b38d77883705"
- file:
    path:  "/usr/lib/restic_0.8.3_linux_amd64"
    state: "directory"
- shell: "bzcat /usr/local/src/restic_0.8.3_linux_amd64.bz2 > /usr/lib/restic_0.8.3_linux_amd64/restic"
  args:
    creates: "/usr/lib/restic_0.8.3_linux_amd64/restic"
- file:
    path:  "/usr/lib/restic_0.8.3_linux_amd64/restic"
    state: "file"
    mode:  "0700"
- file:
     path:  "/usr/local/bin/restic"
     src:   "/usr/lib/restic_0.8.3_linux_amd64/restic"
     state: "link"
    
- get_url:
    url:        "https://github.com/andrewcole/restic-tools/archive/{{ restic_tools_commit }}.tar.gz"
    dest:       "/usr/local/src/restic-tools-{{ restic_tools_commit }}.tar.gz"
    checksum:   "sha256:{{ restic_tools_sha256 }}"
- file:
    path:  "/usr/lib/restic-tools-{{ restic_tools_commit }}"
    state: "directory"
- command: "tar --extract --gzip --file=/usr/local/src/restic-tools-{{ restic_tools_commit }}.tar.gz --strip-components=1 --directory /usr/lib/restic-tools-{{ restic_tools_commit }}"
  args:
    creates: "/usr/lib/restic-tools-{{ restic_tools_commit }}/README.md"
    warn:    "no"
- file:
    path:   "/usr/lib/restic-tools-{{ restic_tools_commit }}/bin/backup"
    state: "file"
    mode:  "0700"
- file:
    path:  "/usr/local/bin/backup"
    src:   "/usr/lib/restic-tools-{{ restic_tools_commit }}/bin/backup"
    state: "link"

- get_url:
    url:        "https://downloads.rclone.org/rclone-v1.39-linux-amd64.zip"
    dest:       "/usr/local/src/rclone-v1.39-linux-amd64.zip"
    checksum:   "sha256:4bb194b67659312d9e33f043e3eb15144ba01877406ee8092438c19b18c2bbcb"
- file:
    path:  "/usr/lib/rclone-v1.39-linux-amd64"
    state: "directory"
- command: "unzip /usr/local/src/rclone-v1.39-linux-amd64.zip -d /usr/lib"
  args:
    creates: "/usr/lib/rclone-v1.39-linux-amd64/rclone"
    warn:    "no"
- file:
    path:   "/usr/lib/rclone-v1.39-linux-amd64/rclone"
    state: "file"
    mode:  "0755"
- file:
    path:  "/usr/local/bin/rclone"
    src:   "/usr/lib/rclone-v1.39-linux-amd64/rclone"
    state: "link"
