---

- set_fact:
    interface: "{{ item }}"
  with_items: "{{ ansible_interfaces }}"
  when:
    - "'.' not in item"
    - "not network_interface.interface is defined"
    - "hostvars[inventory_hostname]['ansible_%s' | format(item)]['macaddress'] is defined"
    - "hostvars[inventory_hostname]['ansible_%s' | format(item)]['macaddress'] == network_interface.hwaddr"

- set_fact:
    interface: "{{ network_interface.interface }}"
  when:
    - "network_interface.interface is defined"

- slack:
    token: "{{ slack_token }}"
    msg:   |
      :information_source: *{{ role_path | basename }} running network-interface-instance.yml on {{ inventory_hostname_short }} with the following variable:*
      
      *network_interface*:
      {{ network_interface | to_nice_json }}
      *interface*: {{ interface }}
  delegate_to: localhost
  when:
    - slack_token is defined


- template:
    src: "ifcfg-en.j2"
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ interface }}"
  register:
    ifcfg_eth
  when:
    - "'en' in interface"

- template:
    src: "ifcfg-en-vlan.j2"
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ interface }}.{{ item.vlan }}"
  register:
    ifcfg_vlan
  with_items:
    "{{ network_interface.vlans }}"
  when:
    - "'en' in interface"
    - "network_interface.vlans is defined"

- template:
    src: "ifcfg-lo.j2"
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ network_interface.interface }}"
  register:
    ifcfg_lo
  when:
    - "'lo' in interface"
  
- service:
    name:  "network"
    state: "restarted"
  when:
    - ifcfg_eth.changed or ifcfg_vlan.changed or ifcfg_lo.changed
