---

- set_fact:
    interface: "{{ item }}{% if network_interface.vlan is defined %}.{{ network_interface.vlan }}{% endif %}"
  with_items: "{{ ansible_interfaces }}"
  when:
    - "'.' not in item"
    - "not network_interface.interface is defined"
    - "hostvars[inventory_hostname]['ansible_%s' | format(item)]['macaddress'] is defined"
    - "hostvars[inventory_hostname]['ansible_%s' | format(item)]['macaddress'] == network_interface.hwaddr"

- set_fact:
    interface: "{{ network_interface.interface }}"
  when:
    - "network_interface.interface is defined"

- slack:
    token: "{{ slack_token }}"
    msg:   |
      :information_source: *{{ role_path | basename }} running network-interface-instance.yml on {{ inventory_hostname_short }} with the following variable:*
      
      *network_interface*:
      {{ network_interface | to_nice_json }}
      *interface*: {{ interface }}
  delegate_to: localhost
  when:
    - slack_token is defined

- template:
    src: "ifcfg-en.j2"
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ interface }}"
  register:
    configuration
  
- service:
    name:  "network"
    state: "restarted"
  when:
    - configuration.changed
