---

- template:
    src: "named.conf.j2"
    dest: "/etc/named.conf"
  register: configuration

- service:
    name:    "{{ item }}"
    state:   "stopped"
  with_items:
    - "named"
  when:
    - "configuration.changed"

- service:
    name:          "{{ item }}"
    enabled:       "yes"
    state:         "started"
    daemon_reload: "yes"
  with_items:
    - "named"
