---

- name: "Install Repositories from Packages"
  yum:
    pkg: "{{ item }}"
    state: present
  with_items:
  - "centos-release-gluster"

- name: "Install Packages"
  yum:
    pkg: "{{ item }}"
    state: present
  with_items:
  - "glusterfs-server"
  - "nfs-utils"
