---

- name: "Install Packages"
  yum:
    pkg: "{{ item }}"
    state: present
  with_items:
    - "lvm2"
  when:
    - "(storage_volumes | default([]) | selectattr('lv','defined') | list | length) > 0"

- name: "Create Volume Group"
  lvg:
    vg:    "{{ item.vg }}"
    pvs:   "{{ item.pvs }}"
    state: "present"
  with_items:
    "{{ storage_lvgs | default([]) }}"

- include_tasks: "{{ role_path | basename }}-{{ role_task }}-instance.yml"
  with_items:
    "{{ storage_volumes | default([]) }}"
  loop_control:
    loop_var: storage
  when:
   - storage.lv is defined
