---

- name: "Install Repositories from Packages"
  yum:
    pkg: "{{ item }}"
    state: present
  with_items:
    - "centos-release-gluster"
  when:
    - "(storage_volumes | selectattr('gv','defined') | list | length) > 0"

- name: "Install Packages"
  yum:
    pkg: "{{ item }}"
    state: present
  with_items:
    - "glusterfs-server"
  when:
    - "(storage_volumes | selectattr('gv','defined') | list | length) > 0"

- name: "Uninstall Packages"
  yum:
    pkg: "{{ item }}"
    state: absent
  with_items:
    - "centos-release-gluster"
    - "glusterfs-server"
  when:
    - "(storage_volumes | selectattr('gv','defined') | list | length) == 0"

- name: "Start Gluster Service"
  service: 
    name:          "{{ item }}"
    enabled:       "yes"
    state:         "started"
    daemon_reload: "yes"
  with_items:
    - "glusterd"

- include_tasks: "{{ role_path | basename }}-{{ role_task }}-instance.yml"
  with_items:
    "{{ storage_volumes }}"
  loop_control:
    loop_var: storage
  when:
   - storage.gv is defined
