---

- include_tasks: "{{ role_path | basename }}-{{ role_task }}-instance.yml"
  with_items:
    "{{ storage_volumes | default([]) }}"
  loop_control:
    loop_var: storage
  when:
   - storage.dependant is defined
   - storage.mnt is defined
