---

- name: "Checking that required variables are set"
  fail:
    msg: "{{ item }} is not defined"
  when:
    - hostvars[inventory_hostname][item] is not defined
  with_items:
    - docker_proxy_network
    - plex_hostname
    - plex_tz
    - plex_ip
    - plex_claim
